name: Production Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  verify:
    name: Verify project state
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run workspace setup
        uses: ./.github/actions/setup-workspace

      - name: Run tests
        run: |
          just test

  deploy:
    name: Deploy new release
    runs-on: ubuntu-latest
    needs: verify
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run setup
        uses: ./.github/actions/setup-workspace

      - name: Set version
        id: set-version
        run: |
          export VERSION=$(jq -r .version specs.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set up GitHub CLI
        shell: bash
        run: |
          sudo apt update
          sudo apt install gh -y
          gh --version

      - name: Generate changelog
        id: changelog
        run: |
          SPEC_VERSION="${{ steps.set-version.outputs.version }}"
          CHANGELOG=$(cat ".github/release/v${SPEC_VERSION}.md")

          {
              echo 'changelog<<EOF'
              echo "$CHANGELOG"
              echo 'EOF'
          } >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ steps.set-version.outputs.version }} \
          --title "${{ steps.set-version.outputs.version }}" \
          --notes "${{ steps.changelog.outputs.changelog }}" \
          --latest

      - name: Publish artifacts
        id: goreleaser-publish
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "latest"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
